2021-01-18 22:44:03,841 INFO    MainThread:59048 [internal.py:wandb_internal():62] W&B internal server running at pid: 59048
2021-01-18 22:44:03,844 DEBUG   HandlerThread:59048 [handler.py:handle_request():54] handle_request: login
2021-01-18 22:44:03,845 DEBUG   SenderThread:59048 [sender.py:send():91] send: request
2021-01-18 22:44:03,846 DEBUG   SenderThread:59048 [sender.py:send_request():100] send_request: login
2021-01-18 22:44:03,854 DEBUG   SenderThread:59048 [connectionpool.py:_new_conn():943] Starting new HTTPS connection (1): api.wandb.ai:443
2021-01-18 22:44:03,953 WARNING MainThread:59048 [internal.py:wandb_internal():116] Internal process interrupt: 1
2021-01-18 22:44:04,105 WARNING MainThread:59048 [internal.py:wandb_internal():116] Internal process interrupt: 2
2021-01-18 22:44:04,105 ERROR   MainThread:59048 [internal.py:wandb_internal():119] Internal process interrupted.
2021-01-18 22:44:04,846 INFO    HandlerThread:59048 [handler.py:finish():267] shutting down handler
2021-01-18 22:44:05,243 DEBUG   SenderThread:59048 [connectionpool.py:_make_request():442] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2021-01-18 22:44:05,248 INFO    SenderThread:59048 [sender.py:send_request_login():147] Login server info: {'cliVersionInfo': {'min_cli_version': '0.8.20', 'max_cli_version': '0.10.13'}}
2021-01-18 22:44:05,258 INFO    SenderThread:59048 [sender.py:finish():548] shutting down sender
2021-01-18 22:44:05,258 INFO    MainThread:59048 [internal.py:handle_exit():137] Internal process exited
