2021-01-18 22:39:04,781 INFO    MainThread:3088 [wandb_init.py:_log_setup():307] Logging user logs to wandb/run-20210118_223904-1wzykyc8/logs/debug.log
2021-01-18 22:39:04,782 INFO    MainThread:3088 [wandb_init.py:_log_setup():308] Logging internal logs to wandb/run-20210118_223904-1wzykyc8/logs/debug-internal.log
2021-01-18 22:39:04,782 INFO    MainThread:3088 [wandb_setup.py:_flush():68] setting env: {}
2021-01-18 22:39:04,782 INFO    MainThread:3088 [wandb_setup.py:_flush():68] setting user settings: {}
2021-01-18 22:39:04,782 INFO    MainThread:3088 [wandb_setup.py:_flush():68] multiprocessing start_methods=fork,spawn,forkserver
2021-01-18 22:39:04,782 WARNING MainThread:3088 [wandb_setup.py:_flush():68] Ignoring settings passed to wandb.setup() which has already been configured.
2021-01-18 22:39:04,817 WARNING MainThread:3088 [wandb_setup.py:__init__():209] Ignoring settings passed to wandb.setup() which has already been configured.
2021-01-18 22:39:09,865 ERROR   MainThread:3088 [wandb_init.py:init():504] error
Traceback (most recent call last):
  File "/home1/quanquan/miniconda3/envs/py3/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 481, in init
    run = wi.init()
  File "/home1/quanquan/miniconda3/envs/py3/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 358, in init
    _backend=backend, _disable_warning=True, _settings=self.settings
  File "/home1/quanquan/miniconda3/envs/py3/lib/python3.6/site-packages/wandb/sdk/wandb_login.py", line 102, in _login
    res = _backend.interface.communicate_login(key, anonymous)
  File "/home1/quanquan/miniconda3/envs/py3/lib/python3.6/site-packages/wandb/interface/interface.py", line 438, in communicate_login
    "Couldn't communicate with backend after %s seconds" % timeout
wandb.errors.error.Error: Couldn't communicate with backend after 5 seconds
2021-01-18 22:39:11,872 INFO    MainThread:3088 [internal.py:handle_exit():137] Internal process exited
